mode = "dark"
accent = "#A6B9DA"
selection = "#44536C"
selection_foreground = "#F0F3FA"
selection_background = "#44536C"
muted = "#B2C0D6"
background = "#222B38"
dark_background = "#1B2330"
darker_background = "#151C27"
lighter_background = "#2D394A"
foreground = "#DEE5F0"
dark_foreground = "#B2C0D6"
light_foreground = "#CAD7EA"
bright_foreground = "#F0F3FA"
hyprland_active_border = "#8A9FBD"
hyprland_inactive_border = "#51627A"
red = "#DEE5F0"
green = "#A6B9DA"
yellow = "#CAD7EA"
orange = "#CAD7EA"
blue = "#A6B9DA"
magenta = "#DEE5F0"
cyan = "#B2C0D6"
brown = "#B2C0D6"
bright_red = "#F0F3FA"
bright_green = "#DEE5F0"
bright_yellow = "#F0F3FA"
bright_blue = "#CAD7EA"
bright_magenta = "#DEE5F0"
bright_cyan = "#A6B9DA"
