[bar]
background = "#222B38"
background-alpha = 0.0
text = "#CAD7EA"
active = "#CAD7EA"
scale-with-font = true
size-horizontal = 26
size-vertical = 28

[hyprland]
active-border = "#8A9FBD"
active-border-foreground = "#8A9FBD"

[controls]
normal-color = "#DEE5F0"
normal-fill-alpha = 0.04
normal-border = "#DEE5F0"
normal-border-width = 1
normal-border-alpha = 0.4
hover-cursor-color = "#A6B9DA"
hover-cursor-fill-alpha = 0.08
hover-cursor-border = "#A6B9DA"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.25
focus-color = "#A6B9DA"
focus-fill-alpha = 0.08
focus-border = "#A6B9DA"
focus-border-width = 1
focus-border-alpha = 0.65
selected-color = "#A6B9DA"
selected-fill-alpha = 0.18
selected-border = "#A6B9DA"
selected-border-width = 0
selected-border-alpha = 1.0
pressed-fill-alpha = 0.22
selection-fill-alpha = 0.35

[spacing]
scale = 1.0
scale-with-font = true

[font]
base-size = 12

[popups]
background = "#2D394A"
background-alpha = 0.88
text = "#DEE5F0"
border = "#51627A"
border-alpha = 1.0
border-width = 1

[tooltip]
background = "#2D394A"
background-alpha = 0.88
text = "#DEE5F0"
border = "#51627A"
border-alpha = 1.0

[notifications]
background = "#2D394A"
background-alpha = 0.88
text = "#DEE5F0"
border = "#51627A"
border-alpha = 1.0
border-width = 1
countdown = "#A6B9DA"

[launcher]
background = "#2D394A"
background-alpha = 0.88
text = "#DEE5F0"
border = "#51627A"
border-alpha = 1.0
scrim = "#151C27"
scrim-alpha = 0.35
selected-background = "#44536C"
selected-background-alpha = 1.0
selected-text = "#F0F3FA"
selected-border = "#A6B9DA"
selected-border-alpha = 0.35

[menu]
background = "#2D394A"
background-alpha = 0.88
text = "#DEE5F0"
border = "#51627A"
border-alpha = 1.0
scrim = "#151C27"
scrim-alpha = 0.35
selected-background = "#44536C"
selected-background-alpha = 1.0
selected-text = "#F0F3FA"
selected-border = "#A6B9DA"
selected-border-alpha = 0.35

[polkit]
background = "#2D394A"
background-alpha = 0.88
text = "#DEE5F0"
text-error = "#D0DAED"
border = "hyprland.active-border"
border-error = "#D0DAED"
border-alpha = 1.0
scrim = "#151C27"
scrim-alpha = 0.5
accent = "#A6B9DA"

[lock]
background = "#222B38"
background-alpha = 0.88
text = "#DEE5F0"
placeholder = "#B2C0D6"
text-error = "#D0DAED"
border = "#51627A"
border-active = "#A6B9DA"
border-error = "#D0DAED"
border-alpha = 1.0
selection = "#A6B9DA"
selection-alpha = 0.15

[image-picker]
scrim = "#151C27"
scrim-alpha = 0.5
text = "#DEE5F0"
selected-border = "#A6B9DA"
selected-border-alpha = 1.0
unselected-border = "#DEE5F0"
unselected-border-alpha = 0.28
